### ISSUE TITLE
Error about spring class not found with Protelis 10.7.0

### ISSUE THREAD

**Issue by jschewebbn** [Protelis/Protelis#174]
I'm using java 8, gradle 4.0 and Protelis 10.7.0.

When I upgraded from 10.6.0 to 10.7.0 I started seeing this exception in my test cases. I have a project "MAP" depends on a project "P2Protelis" which depends on Protelis. Tests in P2Protelis run fine, however tests in MAP fail.
```
java.lang.NoClassDefFoundError: Could not initialize class org.springframework.core.io.support.PathMatchingResourcePatternResolver
	at org.protelis.lang.ProtelisLoader$2.initialValue(ProtelisLoader.java:133)
	at org.protelis.lang.ProtelisLoader$2.initialValue(ProtelisLoader.java:130)
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
	at java.lang.ThreadLocal.get(ThreadLocal.java:170)
	at org.protelis.lang.ProtelisLoader.loadResourcesRecursively(ProtelisLoader
```

**Comment by DanySK** [comment]
Hi @jschewebbn,
the stacktrace looks cut, am I correct? If so, could you send the complete version?

**Comment by jschewebbn** [comment]
Sorry, most everything else below that was outside protelis, so I figured you didn't need it. Here is the full trace. 
```
java.lang.NoClassDefFoundError: Could not initialize class org.springframework.core.io.support.PathMatchingResourcePatternResolver
	at org.protelis.lang.ProtelisLoader$2.initialValue(ProtelisLoader.java:133)
	at org.protelis.lang.ProtelisLoader$2.initialValue(ProtelisLoader.java:130)
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
	at java.lang.ThreadLocal.get(ThreadLocal.java:170)
	at org.protelis.lang.ProtelisLoader.loadResourcesRecursively(ProtelisLoader.java:263)
	at org.protelis.lang.ProtelisLoader.loadResourcesRecursively(ProtelisLoader.java:252)
	at org.protelis.lang.ProtelisLoader.resourceFromURIString(ProtelisLoader.java:244)
	at org.protelis.lang.ProtelisLoader.parseURI(ProtelisLoader.java:240)
	at org.protelis.lang.ProtelisLoader.parse(ProtelisLoader.java:195)
	at com.bbn.map.ap.MapNetworkFactory.createServer(MapNetworkFactory.java:100)
	at com.bbn.map.ap.MapNetworkFactory.createServer(MapNetworkFactory.java:25)
	at com.bbn.protelis.networkresourcemanagement.testbed.Scenario.lambda$new$0(Scenario.java:167)
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:185)
	at com.bbn.protelis.networkresourcemanagement.testbed.Scenario.<init>(Scenario.java:158)
	at com.bbn.map.simulator.Simulation.parseScenario(Simulation.java:498)
	at com.bbn.map.simulator.Simulation.<init>(Simulation.java:293)
	at com.bbn.map.simulator.DNSSimTest.createSimulation(DNSSimTest.java:61)
	at com.bbn.map.simulator.DNSSimTest.setup(DNSSimTest.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy1.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by DanySK** [comment]
Dependencies again?
can you post the output of `./gradlew dependencies` and `./gradlew -q dependencyInsight --configuration testRuntimeClasspath --dependency spring`
(I'm not totally sure about the `testRuntimeClasspath` configuration)

**Comment by jschewebbn** [comment]
[debug.protelis.log](https://github.com/Protelis/Protelis/files/3030417/debug.protelis.log)

**Comment by DanySK** [comment]
This is weird. The class which is not supposed to exist actually exists in `org.springframework:spring-core:5.1.4.RELEASE`, which is (according to your gradle output) correctly pulled in for both compile and runtime.

Do all the tests using Protelis fail consistently?

**Comment by jschewebbn** [comment]
I just ran again to be sure. It looks like all of my tests that try and execute any Protelis code fail with the same error.

**Comment by DanySK** [comment]
This is actually good, as it is reproducible. I am really puzzled though. Can you run your tests using gradle with the `--scan` option? It should publish a detailed report online, I'd like to inspect it.
I don't know if there are things you can't share, in case check out the scan and make sure everything there can be seen by external eyes.

Also: if you add in a test:
```java
System.out.println(Class.forName("org.springframework.core.io.support.PathMatchingResourcePatternResolver");
```
before any Protelis code invocation, does it print `null`?

**Comment by jschewebbn** [comment]
I don't know the details of what is all published with the "--scan" option, so I can't run that without knowing what is sent.

I added your print statement and it results in 
```
org.junit.experimental.theories.internal.ParameterizedAssertionError: testMultinodeSharing("1" <from runIndicies[0]>)
	at org.junit.experimental.theories.Theories$TheoryAnchor.reportParameterizedError(Theories.java:288)
	at org.junit.experimental.theories.Theories$TheoryAnchor$1$1.evaluate(Theories.java:237)
	at org.junit.experimental.theories.Theories$TheoryAnchor.runWithCompleteAssignment(Theories.java:218)
	at org.junit.experimental.theories.Theories$TheoryAnchor.runWithAssignment(Theories.java:204)
	at org.junit.experimental.theories.Theories$TheoryAnchor.runWithIncompleteAssignment(Theories.java:212)
	at org.junit.experimental.theories.Theories$TheoryAnchor.runWithAssignment(Theories.java:202)
	at org.junit.experimental.theories.Theories$TheoryAnchor.evaluate(Theories.java:187)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy1.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/util/ReflectionUtil
	at org.apache.logging.log4j.jcl.LogAdapter.getContext(LogAdapter.java:39)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:46)
	at org.apache.logging.log4j.jcl.LogFactoryImpl.getInstance(LogFactoryImpl.java:40)
	at org.apache.logging.log4j.jcl.LogFactoryImpl.getInstance(LogFactoryImpl.java:55)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:655)
	at org.springframework.core.io.support.PathMatchingResourcePatternResolver.<clinit>(PathMatchingResourcePatternResolver.java:185)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.bbn.map.ap.LeaderElectionTests$TestNetworkSharing.testMultinodeSharing(LeaderElectionTests.java:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.experimental.theories.Theories$TheoryAnchor$2.evaluate(Theories.java:274)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.experimental.theories.Theories$TheoryAnchor$1$1.evaluate(Theories.java:232)
	... 43 more
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.util.ReflectionUtil
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 65 more
```

LeaderElectionTests.java:135 is where I put the print statement using log4j.

**Comment by DanySK** [comment]
Could you use a plain old println? This error looks like `org.apache.logging.log4j.util.ReflectionUtil` cannot be loaded at runtime, which is yet another error with dependencies (maybe related?).

[This is an example scan](https://scans.gradle.com/s/efmd6kqvfm7h2) of a project using Protelis. If you can take a look and see if there is information which should not be shared for the project you are working in, it would be great.

I'm sorry for asking this large amount of information, but unfortunately it's rather hard to debug a build of a software of which I get very limited visibility of code and no possibility to reproduce.

**Comment by jschewebbn** [comment]
Using println I get the same error. Note that the log4j portion of the trace is initialized from `org.springframework.core.io.support.PathMatchingResourcePatternResolver`.

**Comment by DanySK** [comment]
Yeah, yet the root cause is `java.lang.ClassNotFoundException: org.apache.logging.log4j.util.ReflectionUtil`. I wonder if that's the missing part actually.

**Comment by jschewebbn** [comment]
Looking at the dependencies and noting the exception trying to load the spring class; I see the log4j2 version is up to 2.11.2. I bet this is the same error as #162.

**Comment by DanySK** [comment]
GOT IT! Look at: https://stackoverflow.com/questions/52700803/im-getting-noclassdeffounderror-org-apache-logging-log4j-util-reflectionutil

Your runtime dependencies: `org.apache.logging.log4j:log4j-slf4j-impl:2.8.2 -> 2.11.2`, `org.slf4j:slf4j-api:1.7.19 -> 1.7.26`

There is a version mismatch on `com.bbn.protelis:P2Protelis` which needs to get fixed.

A suggestion: if the dependency tree grows too big, the probability of transient dependency version conflicts grows a lot. It is often convenient to change the resolution strategy into "fail on conflict" and solve issues manually to retain control.

**Comment by DanySK** [comment]
Yes you are right @jschewebbn. By the way I gave the same suggestion in #162: better fail on conflict and deal with conflicts manually.

**Comment by jschewebbn** [comment]
I've been having problems with using the failure resolution strategy. I turn on fail and I get an error about slf4j being upgraded to 1.7.26 when I'm only specifying 1.7.25. I haven't been able to track that down

However I did find that if I include spring 5.1.6.RELEASE, then the error about loading the class with the most recent log4j2 goes away.

**Comment by DanySK** [comment]
Since the error is gone, and was not a Protelis bug, I'm closing and marking as invalid.
For the resolution strategy, the idea is that your build will fail for any conflict, and you should resolve it manually by forcing the version of your preference.

**Comment by jschewebbn** [comment]
For forcing versions, I'm trying to force a version and not seeing where the other dependency for a newer version of slf4j is coming in.

BTW I can't reproduce the success I had yesterday with spring 5.1.6. I guess I just can't upgrade log4j2.

**Comment by DanySK** [comment]
Uhmm... as far as I know, once the resolution of a specific version is forced, then that version is taken, no matter who pulls it in. Are you still having two versions in your dependency tree despite forcing?

Very strange behaviour. Not being able to reproduce with Gradle usually implies dirty caches. If your project is on CI, make sure you build it on a clean container/VM every time to prevent such issues (yes, the build will be much slower but it's much safer).

**Comment by jschewebbn** [comment]
Perhaps I just don't know how to force the version. I put in my build dependencies "    compile group: 'org.slf4j', name: 'slf4j-api', version:'1.7.25'". However when I look at the dependencies output I see "org.slf4j:slf4j-api:[1.7.0, 1.8) -> 1.7.26" or "org.slf4j:slf4j-api:1.7.25 -> 1.7.26" for all references to slf4j-api. I would have expected gradle to use 1.7.25 since that's the version that I specified and it should match all ranges that are in the dependencies.

**Comment by DanySK** [comment]
Looks like it's not being forced. The syntax for forcing a specific version is specified [here](https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html#sec:enforcing_dependency_version), though I'm not sure it was the same in Gradle 4.0.

**Comment by jschewebbn** [comment]
Something odd is going on. I added the println statement to P2Protelis and it prints out the class just fine with the log4j dependency at 2.11.2.  I publish that release and make MAP depend on that version of P2Protelis. The same println statement fails in MAP.

**Comment by jschewebbn** [comment]
See email for offline discussion.

**Comment by jschewebbn** [comment]
For anyone else that finds this ticket. It's all about dependencies and configurations. P2Protelis has a runtime dependency on log4j 2.11.2. MAP has a compile time dependency on log4j 2.8.2. This is the problem. Make sure that configurations are consistent across dependent projects.
